/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plans */
        get: operations["list_plans_plans_get"];
        put?: never;
        /** Create Plan */
        post: operations["create_plan_plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_plans__plan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans/{plan_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notes */
        get: operations["list_notes_plans__plan_id__notes_get"];
        put?: never;
        /** Create Note */
        post: operations["create_note_plans__plan_id__notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watchlist */
        get: operations["list_watchlist_watchlist_get"];
        put?: never;
        /** Create Watchlist Item */
        post: operations["create_watchlist_item_watchlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Watchlist Item */
        delete: operations["delete_watchlist_item_watchlist__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist/{item_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Watchlist Item */
        post: operations["refresh_watchlist_item_watchlist__item_id__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Catalyst */
        Catalyst: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Description */
            description: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "earnings" | "macro" | "corporate" | "other";
        };
        /** Citation */
        Citation: {
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Source */
            source: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** Entry */
        Entry: {
            /** Conditions */
            conditions: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "limit" | "market" | "stop_limit";
            /** Levels */
            levels: string[];
        };
        /** ExitLevel */
        ExitLevel: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "scale_out" | "time_stop" | "invalidation";
            /** Portion */
            portion?: number | null;
            /** Price */
            price?: string | null;
            /** Trigger */
            trigger: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NoteCreate */
        NoteCreate: {
            /** Text */
            text: string;
        };
        /** NoteRead */
        NoteRead: {
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Plan Id
             * Format: uuid
             */
            plan_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** Plan */
        Plan: {
            /** Capital */
            capital: string;
            /** Catalysts */
            catalysts: components["schemas"]["Catalyst"][];
            /**
             * Conviction
             * @enum {string}
             */
            conviction: "low" | "medium" | "high";
            entry: components["schemas"]["Entry"];
            /** Exits */
            exits: components["schemas"]["ExitLevel"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Horizon
             * @enum {string}
             */
            horizon: "intraday" | "swing" | "long_term";
            /** Review Cadence */
            review_cadence: string;
            /** Risk Flags */
            risk_flags: components["schemas"]["RiskFlag"][];
            sizing: components["schemas"]["Sizing"];
            /** Sources */
            sources: components["schemas"]["Citation"][];
            stop: components["schemas"]["Stop"];
            /** Thesis */
            thesis: string;
            /** Ticker */
            ticker: string;
        };
        /** PlanCreateRequest */
        PlanCreateRequest: {
            /** Capital */
            capital: number | string;
            /**
             * Horizon
             * @enum {string}
             */
            horizon: "intraday" | "swing" | "long_term";
            /** Ticker */
            ticker: string;
        };
        /** PlanRevisionRead */
        PlanRevisionRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Diff Json */
            diff_json: {
                [key: string]: unknown;
            };
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Plan Id
             * Format: uuid
             */
            plan_id: string;
        };
        /** RiskFlag */
        RiskFlag: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warn";
        };
        /** Sizing */
        Sizing: {
            /** R Value */
            R_value: string;
            /** Dollar Exposure */
            dollar_exposure: string;
            /** Risk Pct */
            risk_pct: number;
            /** Shares */
            shares: number;
        };
        /** Stop */
        Stop: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "technical" | "atr" | "fixed_pct";
            /** Price */
            price: string;
            /** Rationale */
            rationale: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WatchlistItemCreate */
        WatchlistItemCreate: {
            /** Ticker */
            ticker: string;
        };
        /** WatchlistItemRead */
        WatchlistItemRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Plan Id */
            last_plan_id: string | null;
            /** Ticker */
            ticker: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_plans_plans_get: {
        parameters: {
            query?: {
                ticker?: string | null;
                limit?: number;
            };
            header?: {
                "X-User-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_plan_plans_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notes_plans__plan_id__notes_get: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_note_plans__plan_id__notes_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watchlist_watchlist_get: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_watchlist_item_watchlist_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchlistItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_watchlist_item_watchlist__item_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_watchlist_item_watchlist__item_id__refresh_post: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Id"?: string | null;
            };
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanRevisionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
